// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXhpkwQNF9pBhK7ES-WDxT4UGPMU6gsg',
    appId: '1:872762420880:android:c6b4912f29c15fbe80b215',
    messagingSenderId: '872762420880',
    projectId: 'project2-89270',
    storageBucket: 'project2-89270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrxTPMzGdkfdLo6Sjb_aoGY_2BsAMNMc',
    appId: '1:872762420880:ios:2036b2bf1a12c6bd80b215',
    messagingSenderId: '872762420880',
    projectId: 'project2-89270',
    storageBucket: 'project2-89270.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrxTPMzGdkfdLo6Sjb_aoGY_2BsAMNMc',
    appId: '1:872762420880:ios:2036b2bf1a12c6bd80b215',
    messagingSenderId: '872762420880',
    projectId: 'project2-89270',
    storageBucket: 'project2-89270.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );
}
